In [11]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [3]:
my_arr = np.arange(1000000)

In [6]:
my_list = list(range(1000000))

In [7]:
%time for _ in range(10): my_arr2 = my_arr *2

CPU times: user 16.9 ms, sys: 26.7 ms, total: 43.6 ms
Wall time: 43 ms


In [10]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 913 ms, sys: 202 ms, total: 1.11 s
Wall time: 2.91 s


4.1 The NumPy ndarray: A Multidemensional Array Object

In [12]:
data = np.random.randn(2,3)

In [13]:
data

array([[ 1.40603779,  2.1643787 , -0.35162991],
       [-1.84777825, -1.03772813,  2.7882561 ]])

In [14]:
data * 10

array([[ 14.06037793,  21.64378698,  -3.51629915],
       [-18.47778249, -10.37728135,  27.882561  ]])

In [15]:
data + data

array([[ 2.81207559,  4.3287574 , -0.70325983],
       [-3.6955565 , -2.07545627,  5.5765122 ]])

In [17]:
data.shape

(2, 3)

Creating ndarrays

In [18]:
data1 = [6,7.5,8,0,1]

In [19]:
arr1 = np.array(data1)

In [20]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [21]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [22]:
arr2 = np.array(data2)

In [23]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr2.ndim

2

In [25]:
arr2.shape

(2, 4)

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr2.dtype

dtype('int64')

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
np.empty((2,3,2))

array([[[-2.68156159e+154, -1.29073987e-231],
        [ 3.45845952e-323,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]]])

In [34]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Data Types for ndarrays

In [35]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [36]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [38]:
arr1.dtype

dtype('float64')

In [39]:
arr2.dtype

dtype('int32')

In [40]:
arr = np.array([1,2,3,4,5])

In [41]:
arr.dtype

dtype('int64')

In [42]:
float_arr = arr.astype(np.float64)

In [44]:
float_arr.dtype

dtype('float64')

In [45]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [46]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [49]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [50]:
numeric_strings = np.array(['1.25','-9.6','42'], dtype=np.string_)

In [51]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [52]:
int_array = np.arange(10)

In [54]:
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)

In [55]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [56]:
empty_uint32 = np.empty(8, dtype='u4')

In [58]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

## Arithmetic with NumPy Arrays

In [59]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [60]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [61]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [62]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [65]:
arr ** .5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [66]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [68]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [69]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

Basic Indexing and Slicing

In [71]:
arr = np.arange(10)

In [72]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr[5]

5

In [74]:
arr[5:8]

array([5, 6, 7])

In [75]:
arr[5:8]=12

In [76]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [77]:
arr_slice=arr[5:8]

In [78]:
arr_slice

array([12, 12, 12])

In [79]:
arr_slice[1]= 12345

In [80]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [81]:
arr_slice[:]=64

In [82]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [83]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [86]:
arr2d[2]

array([7, 8, 9])

In [87]:
arr2d[0][2]

3

In [88]:
arr2d[0,2]

3

In [89]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [90]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [91]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
old_values = arr3d[0].copy()

In [94]:
arr3d[0] = 42

In [95]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [97]:
arr3d[0] = old_values

In [98]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [99]:
arr3d[1,0]

array([7, 8, 9])

In [101]:
x = arr3d[1]

In [102]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [103]:
x[0]

array([7, 8, 9])

Indexing with slices

In [104]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [105]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [106]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
arr2d[1,:2]

array([4, 5])

In [111]:
arr2d[:2,2]

array([3, 6])

In [112]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [113]:
arr2d[:2,1:]=0

In [114]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing

In [115]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [116]:
data = np.random.randn(7,4)

In [117]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [118]:
data

array([[-0.81109607,  1.19884316, -2.52739318, -0.20069947],
       [ 1.78418832, -0.21514906,  0.27391253,  1.22897174],
       [-0.7382961 ,  0.70378759,  1.28114781, -0.08135589],
       [-0.02989874, -1.24903559,  0.27669705, -0.65752692],
       [ 0.74995126, -1.50726867,  0.5064997 ,  0.616261  ],
       [-1.70751171,  1.5307447 ,  0.61777919, -0.28201448],
       [-2.58304914, -0.09556923,  0.52507345,  0.25676312]])

In [119]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [121]:
data[names=='Bob']

array([[-0.81109607,  1.19884316, -2.52739318, -0.20069947],
       [-0.02989874, -1.24903559,  0.27669705, -0.65752692]])

In [123]:
data[names == 'Bob',2:]

array([[-2.52739318, -0.20069947],
       [ 0.27669705, -0.65752692]])

In [124]:
data[names == 'Bob', 3]

array([-0.20069947, -0.65752692])

In [125]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [126]:
data[~(names == 'Bob')]

array([[ 1.78418832, -0.21514906,  0.27391253,  1.22897174],
       [-0.7382961 ,  0.70378759,  1.28114781, -0.08135589],
       [ 0.74995126, -1.50726867,  0.5064997 ,  0.616261  ],
       [-1.70751171,  1.5307447 ,  0.61777919, -0.28201448],
       [-2.58304914, -0.09556923,  0.52507345,  0.25676312]])

In [127]:
cond = names == 'Bob'

In [128]:
data[~cond]

array([[ 1.78418832, -0.21514906,  0.27391253,  1.22897174],
       [-0.7382961 ,  0.70378759,  1.28114781, -0.08135589],
       [ 0.74995126, -1.50726867,  0.5064997 ,  0.616261  ],
       [-1.70751171,  1.5307447 ,  0.61777919, -0.28201448],
       [-2.58304914, -0.09556923,  0.52507345,  0.25676312]])

In [130]:
mask = (names == 'Bob') | (names == 'Will')

In [131]:
mask

array([ True, False,  True,  True,  True, False, False])

In [132]:
data[data<0] = 0

In [133]:
data

array([[0.        , 1.19884316, 0.        , 0.        ],
       [1.78418832, 0.        , 0.27391253, 1.22897174],
       [0.        , 0.70378759, 1.28114781, 0.        ],
       [0.        , 0.        , 0.27669705, 0.        ],
       [0.74995126, 0.        , 0.5064997 , 0.616261  ],
       [0.        , 1.5307447 , 0.61777919, 0.        ],
       [0.        , 0.        , 0.52507345, 0.25676312]])

In [134]:
data[names != 'Joe'] = 7

In [135]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.78418832, 0.        , 0.27391253, 1.22897174],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.5307447 , 0.61777919, 0.        ],
       [0.        , 0.        , 0.52507345, 0.25676312]])

Fancy Indexing

In [137]:
arr = np.empty((8,4))

In [138]:
for i in range(8):
    arr[i] = i

In [139]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [140]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [141]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [142]:
arr = np.arange(32).reshape((8,4))

In [144]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [146]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [149]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

Transposing Arrays and Swapping Axes

In [151]:
arr = np.arange(15).reshape((3,5))

In [152]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [153]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [154]:
arr = np.random.randn(6,3)

In [155]:
arr

array([[-0.87571626, -1.81483711, -0.65490055],
       [-1.80478856,  1.72809052, -1.00171341],
       [ 1.01585045, -2.91713485, -0.38746758],
       [ 0.75187197,  0.31554055,  1.77592096],
       [ 2.28297328, -0.03070502, -0.6983676 ],
       [ 0.10257598,  0.9350705 ,  0.13781924]])

In [156]:
np.dot(arr.T, arr)

array([[10.84389316, -4.22986526,  1.7428264 ],
       [-4.22986526, 15.76447179,  1.29847073],
       [ 1.7428264 ,  1.29847073,  5.24306231]])

In [157]:
arr = np.arange(16).reshape((2,2,4))

In [158]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [159]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [160]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [161]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 4.2 Universal Function: Fast Element-Wise Array Functions

In [162]:
arr = np.arange(10)

In [163]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [165]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [166]:
x = np.random.randn(8)

In [167]:
y = np.random.randn(8)

In [168]:
x

array([ 1.54137717,  0.75283762,  0.15470439, -0.53603185,  0.13758836,
        1.02917013,  0.01181374,  0.48947007])

In [169]:
y

array([-1.30669003, -2.13545805,  1.78722155,  0.33109851, -0.12411188,
       -0.80767575, -0.85410102, -0.43028173])

In [170]:
np.maximum(x,y)

array([1.54137717, 0.75283762, 1.78722155, 0.33109851, 0.13758836,
       1.02917013, 0.01181374, 0.48947007])

In [171]:
arr = np.random.randn(7) * 5

In [172]:
arr

array([ 6.31499929, -6.56401078,  5.53840029,  4.4607808 , -4.15729029,
        1.52741917,  0.76831102])

In [173]:
remainder, whole_part = np.modf(arr)

In [175]:
remainder

array([ 0.31499929, -0.56401078,  0.53840029,  0.4607808 , -0.15729029,
        0.52741917,  0.76831102])

In [176]:
whole_part

array([ 6., -6.,  5.,  4., -4.,  1.,  0.])

In [177]:
arr

array([ 6.31499929, -6.56401078,  5.53840029,  4.4607808 , -4.15729029,
        1.52741917,  0.76831102])

In [178]:
whole_part

array([ 6., -6.,  5.,  4., -4.,  1.,  0.])

In [179]:
arr

array([ 6.31499929, -6.56401078,  5.53840029,  4.4607808 , -4.15729029,
        1.52741917,  0.76831102])

In [180]:
np.sqrt(arr)

<ipython-input-180-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([2.51296623,        nan, 2.35338061, 2.11205606,        nan,
       1.23588801, 0.87653352])

In [181]:
np.sqrt(arr,arr)

<ipython-input-181-e3ca18b15869>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr,arr)


array([2.51296623,        nan, 2.35338061, 2.11205606,        nan,
       1.23588801, 0.87653352])

## Array-Oriented Programming with Arrays

In [182]:
points = np.arange(-5,5,0.001) # 1000 equally spaced points

In [183]:
xs,ys = np.meshgrid(points,points)

In [184]:
ys

array([[-5.   , -5.   , -5.   , ..., -5.   , -5.   , -5.   ],
       [-4.999, -4.999, -4.999, ..., -4.999, -4.999, -4.999],
       [-4.998, -4.998, -4.998, ..., -4.998, -4.998, -4.998],
       ...,
       [ 4.997,  4.997,  4.997, ...,  4.997,  4.997,  4.997],
       [ 4.998,  4.998,  4.998, ...,  4.998,  4.998,  4.998],
       [ 4.999,  4.999,  4.999, ...,  4.999,  4.999,  4.999]])

In [187]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [189]:
z

array([[7.07106781, 7.07036074, 7.06965374, ..., 7.06894681, 7.06965374,
        7.07036074],
       [7.07036074, 7.0696536 , 7.06894653, ..., 7.06823953, 7.06894653,
        7.0696536 ],
       [7.06965374, 7.06894653, 7.06823938, ..., 7.06753231, 7.06823938,
        7.06894653],
       ...,
       [7.06894681, 7.06823953, 7.06753231, ..., 7.06682517, 7.06753231,
        7.06823953],
       [7.06965374, 7.06894653, 7.06823938, ..., 7.06753231, 7.06823938,
        7.06894653],
       [7.07036074, 7.0696536 , 7.06894653, ..., 7.06823953, 7.06894653,
        7.0696536 ]])

In [190]:
import matplotlib.pyplot as plt

In [ ]:
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()

plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

Expressing Conditional Logic as Array Operations

In [193]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])

In [194]:
yarr = np.array([2.1,2.2,2.3,2.4,2.5])

In [195]:
cond = np.array([True,False,True,True,False])

In [196]:
result = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]

In [198]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [199]:
result = np.where(cond, xarr, yarr)

In [200]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [201]:
arr = np.random.randn(4,4)

In [206]:
arr

array([[ 0.53087539,  0.70499001, -0.8718536 , -3.16126479],
       [-0.37948028, -1.87802557,  0.56227881, -0.64651964],
       [-0.41737425, -1.28865328,  0.28822492,  0.90558056],
       [-1.10593509,  0.94636134, -1.7175025 , -1.25484485]])

In [207]:
arr >0 

array([[ True,  True, False, False],
       [False, False,  True, False],
       [False, False,  True,  True],
       [False,  True, False, False]])

In [208]:
np.where(arr >0,2,-2)

array([[ 2,  2, -2, -2],
       [-2, -2,  2, -2],
       [-2, -2,  2,  2],
       [-2,  2, -2, -2]])

In [209]:
np.where(arr>0,2,arr)

array([[ 2.        ,  2.        , -0.8718536 , -3.16126479],
       [-0.37948028, -1.87802557,  2.        , -0.64651964],
       [-0.41737425, -1.28865328,  2.        ,  2.        ],
       [-1.10593509,  2.        , -1.7175025 , -1.25484485]])

Mathematical and Statistical Methods

In [210]:
arr = np.random.randn(5,4)

In [211]:
arr

array([[-0.12523487, -1.19475306,  0.3629779 , -0.67102247],
       [ 1.03133336,  0.18635853,  0.63605371, -1.51499484],
       [-1.0077784 ,  0.67878216, -0.17329843,  1.14705997],
       [-0.03026326,  0.14649768, -1.51161561,  0.3413511 ],
       [-0.425183  ,  2.31207441, -1.49692168, -1.67518862]])

In [212]:
arr.mean()

-0.14918827082673675

In [214]:
np.mean(arr)

-0.14918827082673675

In [215]:
arr.sum()

-2.9837654165347347

In [216]:
arr.mean(axis=1)

array([-0.40700813,  0.08468769,  0.16119133, -0.26350752, -0.32130472])

In [217]:
arr.sum(axis=0)

array([-0.55712618,  2.12895972, -2.18280411, -2.37279485])

In [218]:
arr = np.array([0,1,2,3,4,5,6,7])

In [219]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [220]:
array = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [221]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [222]:
arr.cumsum(axis=0)

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [224]:
array.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

Methods for Boolean Arrays



In [225]:
arr=np.random.randn(100)

In [226]:
(arr>0).sum() #Number of positive values

50

In [227]:
bools = np.array([False,False,True,False])

In [ ]:
bools