In [11]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [3]:
my_arr = np.arange(1000000)

In [6]:
my_list = list(range(1000000))

In [7]:
%time for _ in range(10): my_arr2 = my_arr *2

CPU times: user 16.9 ms, sys: 26.7 ms, total: 43.6 ms
Wall time: 43 ms


In [10]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 913 ms, sys: 202 ms, total: 1.11 s
Wall time: 2.91 s


4.1 The NumPy ndarray: A Multidemensional Array Object

In [12]:
data = np.random.randn(2,3)

In [13]:
data

array([[ 1.40603779,  2.1643787 , -0.35162991],
       [-1.84777825, -1.03772813,  2.7882561 ]])

In [14]:
data * 10

array([[ 14.06037793,  21.64378698,  -3.51629915],
       [-18.47778249, -10.37728135,  27.882561  ]])

In [15]:
data + data

array([[ 2.81207559,  4.3287574 , -0.70325983],
       [-3.6955565 , -2.07545627,  5.5765122 ]])