In [11]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [3]:
my_arr = np.arange(1000000)

In [6]:
my_list = list(range(1000000))

In [7]:
%time for _ in range(10): my_arr2 = my_arr *2

CPU times: user 16.9 ms, sys: 26.7 ms, total: 43.6 ms
Wall time: 43 ms


In [10]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 913 ms, sys: 202 ms, total: 1.11 s
Wall time: 2.91 s


4.1 The NumPy ndarray: A Multidemensional Array Object

In [12]:
data = np.random.randn(2,3)

In [13]:
data

array([[ 1.40603779,  2.1643787 , -0.35162991],
       [-1.84777825, -1.03772813,  2.7882561 ]])

In [14]:
data * 10

array([[ 14.06037793,  21.64378698,  -3.51629915],
       [-18.47778249, -10.37728135,  27.882561  ]])

In [15]:
data + data

array([[ 2.81207559,  4.3287574 , -0.70325983],
       [-3.6955565 , -2.07545627,  5.5765122 ]])

In [17]:
data.shape

(2, 3)

Creating ndarrays

In [18]:
data1 = [6,7.5,8,0,1]

In [19]:
arr1 = np.array(data1)

In [20]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [21]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [22]:
arr2 = np.array(data2)

In [23]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr2.ndim

2

In [25]:
arr2.shape

(2, 4)

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr2.dtype

dtype('int64')

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
np.empty((2,3,2))

array([[[-2.68156159e+154, -1.29073987e-231],
        [ 3.45845952e-323,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]]])

In [34]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])